# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Geschiedenis van België
email: geschiedenisvan@outlook.be
description: >- # this means to ignore newlines until "baseurl:"
  Geschiedenisleerkracht die moedige pogingen doet om het waarom en het hoe van de Belgische geschiedenis te ontrafelen.
baseurl: "/geschiedenisvan" # the subpath of your site, e.g. /blog
url: "https://glnvb.github.io" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
 - luisteren.markdown
 - shownotes.markdown
 - discord.markdown
 - over.markdown

author_logo: profile.png
post_logo: posts.png
home_logo: home.png
author: Tim Gistelinck
author_bio: 
author_email: ""
author_location: 
author_website_url: ""
typewrite-text: PODCAST

minima:
  social_links:
   twitter: van_belgie
   github: glnvb
   stackoverflow: ""
   dribbble: jekyll
   facebook: jekyll
   flickr: jekyll
   instagram: jekyll
   linkedin: jekyll
   pinterest: jekyll
   telegram: jekyll
   microdotblog: jekyll
   keybase: jekyll
   youtube: 
   youtube_channel: UC5iU3y8mdhN1xAte7y8CSCA
   youtube_channel_name: CloGeschiedenis van België

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# formspree (contact form)
formspree_email: geschiedenisvan@outlook.com

# syntax highlighter
# markdown: kramdown
# highlighter: rouge
# permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false

# algolia search
# algolia:
#   application_id: D9WA1YKTRQ
#   index_name: blog_posts # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'article'
#   search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
# paginate: 6
# per_page: 6
# paginate_path: "/blog/page/:num/"



# Build settings
theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
