name: Algolia push records
on:
  push:
    branches:
     - main
  jobs:
   runs-on: ubuntu-latest
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set up ruby
        uses: actions/setup-ruby@v1
      - name: Install dependencies and push records
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}          
          
