name: update schedule daily
on:
  schedule:
    - cron: "0 0 * * *"
    branches:
     - main
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
